name: Create Issues from Comment

on:
  issue_comment:
    types: [created]

jobs:
  create-issues:
    if: contains(github.event.comment.body, '/create_issues')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests aiohttp

    - name: Extract issues from comment
      id: extract_issues
      run: |
        COMMENT_BODY="${{ github.event.comment.body }}"
        ISSUES=$(echo "$COMMENT_BODY" | grep -oP '/create_issues\s*\K\[\[.*?\]\]' | head -1)
        echo "ISSUES=$ISSUES" >> $GITHUB_ENV
        echo "COMMENT_ID=${{ github.event.comment.id }}" >> $GITHUB_ENV

    - name: Create scripts directory
      run: mkdir -p scripts

    - name: Download create_issues.py
      run: curl -L https://github.com/nimishchaudhari/openhands_workflow/raw/main/scripts/create_issues.py -o scripts/create_issues.py

    - name: Create "Work in Progress" comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        COMMENT_ID: ${{ env.COMMENT_ID }}
      run: |
        curl -X POST \
        -H "Authorization: token $GITHUB_TOKEN" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/issues/comments/$COMMENT_ID" \
        -d '{"body": "Work in progress..."}'

    - name: Create issues
      env:
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUES: ${{ env.ISSUES }}
        COMMENT_ID: ${{ env.COMMENT_ID }}
      run: python scripts/create_issues.py
